# Generated by Django 6.0.4 on 2026-04-17 22:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=api.models.generate_uuid_v7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('gender_probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sample_size', models.IntegerField()),
                ('age', models.IntegerField()),
                ('age_group', models.CharField(max_length=20)),
                ('country_id', models.CharField(max_length=10, null=True)),
                ('country_probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
