# Generated by Django 6.0.4 on 2026-04-23 15:12

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('gender_probability', models.FloatField()),
                ('age', models.IntegerField()),
                ('age_group', models.CharField(max_length=20)),
                ('country_id', models.CharField(max_length=10, null=True)),
                ('country_name', models.CharField(max_length=100, null=True)),
                ('country_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gender'], name='api_profile_gender_8edb79_idx'), models.Index(fields=['age'], name='api_profile_age_d97b9b_idx'), models.Index(fields=['country_id'], name='api_profile_country_65dc5e_idx'), models.Index(fields=['age_group'], name='api_profile_age_gro_f7046d_idx'), models.Index(fields=['created_at'], name='api_profile_created_7369c0_idx')],
            },
        ),
    ]
